### ISSUE TITLE
Imprecise text  in Protocol Flow

### ISSUE THREAD

**Issue by nklomp** [decentralized-identity/jwt-vc-presentation-profile#55]
I had some comments from our developers, which I think have merit about the below text in https://identity.foundation/jwt-vc-presentation-profile/#the-protocol-flow

> Upon receiving the ID Token and VP Token, Verifier performs necessary checks such as DID resolution, signature validation, Linked Domain validation, revocation checks, **etc.** and sends an **acknowledgement** of receipt back to the Wallet.

What is meant with the 'etc.'? Since this is a profile it might make sense to be explicit about the actual checks that need to be performed instead of listing a few and suggesting more (etc.) needs to be done.

What is meant with the 'acknowledgement'? It is also listed in the flow diagram. Given it is an HTTP post does that mean a HTTP 2xx response code, or does it mean something else?

**Comment by jischr** [comment]
Great points. Let me draft something up to address. 

Etc. can be updated to list out all of the checks. I was originally thinking to be brief here as it is supposed to be more of an overview. But I agree that it should be clarified to be explicit.

Thanks for bringing up Acknowledgement. I actually think this portion should be deleted/revised since an acknowledgement other than a 2xx status code hasnt been discussed. Will Update.

**Comment by Sakurann** [comment]
I think we need a separate section that describes all of the checks that need to be performed, which will be referenced from the overview section.

yes, acknowledgement is 2xx response code.
